### ISSUE TITLE
Use MXSymbolSetAttrs instead of MXSymbolSetAttr in MXNet::Symbol#set_attributes

### ISSUE THREAD

**Issue by mrkn** [mrkn/mxnet.rb#40]
The current implementation of `MXNet:Symbol#set_attributes` uses `MXSymbolSetAttr` for each key-value pair of specified attributes.
It can be rewritten to call `MXSymbolSetAttrs`.

**Comment by toddsundsted** [comment]
Opened https://github.com/mrkn/mxnet.rb/pull/41. 

It turns out `MXSymbolSetAttrs` does not exist. The Python code was (I believe, incorrectly) modified, however the modified method is redefined in all existing base classes, so the error wasn't noticed. In any case, this change achieves the objectives.

**Comment by mrkn** [comment]
Resolved by #41
